### ISSUE TITLE
does not show banner created in admob

### ISSUE THREAD

**Issue by zero2000** [FrogSquare/GodotAds#13]
hello, I wish you could guide me in esprunto, I have tested with the example codes offered by admoby if it shows the types of sample banner, but the problem arises when entering my own codes that admob gives me and it is at that time That doesn't show it.

seeing admob, it gives me the id of the application, apart from the id of the banner.

Here is what debug shows me

ppbg@ppbg-Lenovo-ideapad-320-15ABR:~/game_engine/godot/platform/android/java$ adb -d logcat godot:V GoogleService:V FrogSquare:V DEBUG:V AndroidRuntime:V ValidateServiceOp:V *:S
--------- beginning of system
--------- beginning of main
07-25 00:13:02.411 21316 21338 I godot   : Loading Android module: org/godotengine/godot/GodotAds
07-25 00:13:02.412 21316 21338 I godot   : Loading Android module: org/godotengine/godot/AdMob
07-25 00:13:02.417 21316 21338 I godot   : Loading Android module: org/godotengine/godot/SQLBridge
07-25 00:13:02.420 21316 21338 D godot   : SQLBridge:Initialized
07-25 00:13:02.499 21316 21338 I godot   : OpenGL ES 2.0 Renderer: Mali-T830
07-25 00:13:08.738 21316 21316 D FrogSquare: AdMob::Initialized
07-25 00:13:11.557 21316 21338 I godot   : Error al cargar datos
07-25 00:13:13.742 21316 21316 W FrogSquare: AdMob:Interstitial:onAdFailedToLoad:3
07-25 00:13:15.588 21316 21316 D FrogSquare: AdMob:Interstitial:NotLoaded
07-25 00:13:19.650 21316 21316 D FrogSquare: AdMob::Initialized
07-25 00:13:21.067 21316 21316 W FrogSquare: AdMob:Interstitial:onAdFailedToLoad:3
07-25 00:13:24.938 21316 21316 D FrogSquare: AdMob:Interstitial:NotLoaded
07-25 00:13:28.098 21316 21316 D FrogSquare: AdMob::Initialized
07-25 00:13:28.574 21316 21316 W FrogSquare: AdMob:Interstitial:onAdFailedToLoad:3
07-25 00:13:33.414 21316 21316 D FrogSquare: AdMob:Interstitial:NotLoaded
07-25 00:13:37.467 21316 21316 D FrogSquare: AdMob::Initialized
07-25 00:13:37.853 21316 21316 W FrogSquare: AdMob:Interstitial:onAdFailedToLoad:3
07-25 00:13:42.754 21316 21316 D FrogSquare: AdMob:Interstitial:NotLoaded
07-25 00:13:46.798 21316 21316 D FrogSquare: AdMob::Initialized
07-25 00:13:47.703 21316 21316 W FrogSquare: AdMob:Interstitial:onAdFailedToLoad:3
07-25 00:13:52.098 21316 21316 D FrogSquare: AdMob:Interstitial:NotLoaded
07-25 00:13:56.141 21316 21316 D FrogSquare: AdMob::Initialized
07-25 00:13:56.572 21316 21316 W FrogSquare: AdMob:Interstitial:onAdFailedToLoad:3
07-25 00:14:01.451 21316 21316 D FrogSquare: AdMob:Interstitial:NotLoaded
07-25 00:14:05.494 21316 21316 D FrogSquare: AdMob::Initialized
07-25 00:14:05.944 21316 21316 W FrogSquare: AdMob:Interstitial:onAdFailedToLoad:3
07-25 00:14:10.826 21316 21316 D FrogSquare: AdMob:Interstitial:NotLoaded
07-25 00:14:14.858 21316 21316 D FrogSquare: AdMob::Initialized
07-25 00:14:15.686 21316 21316 W FrogSquare: AdMob:Interstitial:onAdFailedToLoad:3
07-25 00:14:20.163 21316 21316 D FrogSquare: AdMob:Interstitial:NotLoaded
07-25 00:14:24.202 21316 21316 D FrogSquare: AdMob::Initialized
07-25 00:14:24.718 21316 21316 W FrogSquare: AdMob:Interstitial:onAdFailedToLoad:3
07-25 00:14:32.841 21316 21316 D FrogSquare: AdMob:Interstitial:NotLoaded
07-25 00:14:36.928 21316 21316 D FrogSquare: AdMob::Initialized
07-25 00:14:37.917 21316 21316 W FrogSquare: AdMob:Interstitial:onAdFailedToLoad:3
07-25 00:14:42.191 21316 21316 D FrogSquare: AdMob:Interstitial:NotLoaded
07-25 00:14:46.236 21316 21316 D FrogSquare: AdMob::Initialized
07-25 00:14:46.724 21316 21316 W FrogSquare: AdMob:Interstitial:onAdFailedToLoad:3

I hope your guide to solve this problem

**Comment by RameshRavone** [comment]
Error code 3 is `ERROR_CODE_NO_FILL` which means there are no ads to show for your unit_id, If you just created the UnitID give it some time,

Sometimes it also happens if your app is in play store beat and you use the local build to test,

**Comment by zero2000** [comment]
> 
> 
> Error code 3 is `ERROR_CODE_NO_FILL` which means there are no ads to show for your unit_id, If you just created the UnitID give it some time,
> 
> Sometimes it also happens if your app is in play store beat and you use the local build to test,

I created the banner 8 days ago, or it will be that my app is in beta ..
You will have to see that.
