### ISSUE TITLE
gradlew Build Failed

### ISSUE THREAD

**Issue by tamoorashiq** [FrogSquare/GodotAds#3]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\godot\platform\android\java\build.gradle' line: 5

* What went wrong:
Could not compile build file 'C:\godot\platform\android\java\build.gradle'.
> startup failed:
  build file 'C:\godot\platform\android\java\build.gradle': 5: unexpected char: '\' @ line 5, column 10.
        dirs 'C:\godot\modules\GodotAds/libs','C:\Users\Khaleef\Desktop\Godot_v3.0.6-stable_win64.exe\godot\modules\GodotAds/res'
              ^

  1 error

**Comment by tamoorashiq** [comment]
It progressed but now i'm stuck here.

```Download https://maven.google.com/com/google/android/gms/play-services-wearable/maven-metadata.xml

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'java'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find :unity-ads:.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 47s```

**Comment by RameshRavone** [comment]
Have you downloaded [](https://github.com/Unity-Technologies/unity-ads-android/releases/download/2.1.1/unity-ads.aar) and placed in `${GODOT_ROOT}/modules/GodotAds/libs/`

**Comment by tamoorashiq** [comment]
It works . But can tell me the version of "com.google.android.gms"  as i have to set same version for other modules as well because it fails when i try to build after adding google play game service , ads modules.

**Comment by RameshRavone** [comment]
Hmmm, it seems I'm still using the older versions of `com.google.android.gms`, should bump that to latest.

**Comment by RameshRavone** [comment]
I'll make a push later today. It shouldn't create any probs though.

we just need to change the gms version for `Vungle` which is `com.google.android.gms:play-services-location:15.0.1`

the other `com.google.android.gms:play-services-ads:15.0.1` is the latest so this is fine
