### ISSUE TITLE
Upgrade to 3.1

### ISSUE THREAD

**Issue by DDru** [FrogSquare/GodotAds#7]
Please update to Godot 3.1 or update docs (how to use) because now (in 3.1) any ads-singletons not existing
var Unityads = Engine.get_singleton("GDUnityAds") equals [Object:null]

**Comment by RameshRavone** [comment]
Done

**Comment by AlbertMontagutCasero** [comment]
Lol, not done dude
![](https://imgur.com/C9wn3Ee.png)

**Comment by RameshRavone** [comment]
😕 That is clearly the wrong way to initialize the module, please refer the README.md and module is for android only not desktop..
