### ISSUE TITLE
I am getting an error compiling godot for android when including this module.

### ISSUE THREAD

**Issue by devinholdiman** [FrogSquare/GodotAds#9]
I am trying to compile the export templet for android including this https://github.com/FrogSquare/GodotAds module and scons is giving me the following error can someone help.     

AttributeError: 'SConsEnvironment' object has no attribute 'android_add_maven_repository':
  File "C:\Users\Devin\Downloads\godot-master\godot-master\SConstruct", line 403:
    config.configure(env)
  File "./modules/GodotAds\config.py", line 59:
    env.android_add_maven_repository('url "https://maven.google.com/%22%27)

**Comment by RameshRavone** [comment]
Recent changes to the master branch broke pretty much all android module
for godot 3.1 => 3.2, so try using 3.1 stable for now or wait till new
updates are pushed out

**Comment by devinholdiman** [comment]
Thanks.
